general:
  ontology: data/go.owl
  graph-gen-method: taxonomy_rels

rgcn-params:
  lr: 0.0001
  n-hidden: 3
  batch-size: 32
  epochs: 32
  dropout: 0.2
  regularization: 0
  num-bases: -1
  normalization: False
  self-loop: False
  min-edges: 100
  seed: 0

files:
  train_inter_file: "data/4932.train_interactions.pkl"
  valid_inter_file: "data/4932.valid_interactions.pkl"
  test_inter_file: "data/4932.test_interactions.pkl"
  data_file: "data/4932.annotations.tsv"
  output_model: "data/taxRels_yeast_model.pt"