name: mowl
channels:
  - conda-forge
dependencies:
  - python=3.8
  - click
  - deprecated
  - gensim
  - gradle
  - JPype1=1.3.0
  - matplotlib
  - networkx
  - numpy
  - openjdk
  - pandas
  - pytorch
  - pyyaml
  - requests
  - scikit-learn
  - scipy  
  - tqdm
  - urllib3
  - pip
  - pip:
    - pykeen==1.9.0
    - temp
