name: mowldev
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.9
  - cairo
  - deprecated
  - numpy
  - networkx
  - click
  - grpcio
  - JPype1
  - pandas
  - protobuf
  - pytest
  - pyyaml
  - requests
  - scipy
  - scikit-learn
  - urllib3
  - pytorch
  - gensim
  - openjdk
  - gradle
  - pip
  - pip:
    - pykeen
    - sphinx-rtd-theme
    - nose
    - nose-exclude
    - coverage
    - flake8
    - autopep8
  - jupyter
  - ipykernel
  - sphinx
  - sphinx-gallery
  - nbsphinx
  - mock