general:
  ontology: data/ppi/go.owl
  graph-gen-method: owl2vec_star
  use-case: ppi  
rgcn-params:
  lr: 0.00001
  n-hidden: 3
  batch-size: 128
  epochs: 64
  dropout: 0.5
  regularization: 0
  num-bases: -1
  normalization: True
  self-loop: False
  min-edges: 100
  seed: 0

files:
  train_inter_file: "data/ppi/4932.train_interactions.pkl"
  valid_inter_file: "data/ppi/4932.valid_interactions.pkl"
  test_inter_file: "data/ppi/4932.test_interactions.pkl"
  data_file: "data/ppi/4932.annotations.tsv"
  terms_file: "data/ppi/4932.terms.tsv"
  precomputed_edges_file: "data/ppi/4932.edges_owl2vec.pkl"
  output_model: "data/ppi/owl2vec_yeast_model.pt"


rgcn-params_tuned:
  lr: 0.004859640038126263
  n-hidden: 4
  batch-size: 16
  epochs: 32
  dropout: 0.3
  regularization: 2.823590775827415e-05
  num-bases: -1
  normalization: True
  self-loop: False
  min-edges: 100
  seed: 0

