general:
  ontology: data/ppi/go.owl
  graph-gen-method: taxonomy
  use-case: ppi

rgcn-params:
  lr: 0.0001
  n-hidden: 5
  batch-size: 32
  epochs: 32
  dropout: 0.5
  regularization: 0.0001
  num-bases: -1
  normalization: True
  self-loop: False
  min-edges: 100
  seed: 0

files:
  train_inter_file: "data/ppi/4932.train_interactions.pkl"
  valid_inter_file: "data/ppi/4932.valid_interactions.pkl"
  test_inter_file: "data/ppi/4932.test_interactions.pkl"
  data_file: "data/ppi/4932.annotations.tsv"
  terms_file: "data/ppi/4932.terms.tsv"
  precomputed_edges_file: "data/ppi/4932.edges_tax.pkl"
  output_model: "data/ppi/tax_yeast_model.pt"