general:
  ontology: data/ppi/go.owl
  graph-gen-method: owl2vec_star
  use-case: ppi
  
rgcn-params:
  lr: 0.0001
  n-hidden: 2
  batch-size: 32
  epochs: 32
  dropout: 0.5
  regularization: 0.005
  num-bases: -1
  normalization: True
  self-loop: False
  min-edges: 100
  seed: 0

files:
  train_inter_file: "data/ppi/9606.train_interactions.pkl"
  valid_inter_file: "data/ppi/9606.valid_interactions.pkl"
  test_inter_file: "data/ppi/9606.test_interactions.pkl"
  data_file: "data/ppi/9606.annotations.tsv"
  terms_file: "data/ppi/9606.terms.tsv"
  precomputed_edges_file: "data/ppi/9606.edges_owl2vec.pkl"
  output_model: "data/ppi/owl2vec_human_model.pt"