general:
  ontology: data/go.owl
  graph-gen-method: owl2vec_star
  
rgcn-params:
  lr: 0.0001
  n-hidden: 3
  batch-size: 32
  epochs: 32
  dropout: 0.5
  regularization: 0.01
  num-bases: -1
  normalization: True
  self-loop: True
  min-edges: 100
  seed: 0

files:
  train_inter_file: "data/9606.train_interactions.pkl"
  valid_inter_file: "data/9606.valid_interactions.pkl"
  test_inter_file: "data/9606.test_interactions.pkl"
  data_file: "data/9606.annotations.tsv"
  output_model: "data/owl2vec_human_model.pt"