name: mowl39
channels:
  - conda-forge
dependencies:
  - python=3.9
  - click
  - deprecated
  - gradle
  - JPype1=1.5.1
  - pandas
  - pytorch
  - pyyaml
  - requests
  - scikit-learn
  - tqdm
  - urllib3
  - pip
  - pip:
    - gensim>=4.3.0
    - scipy<1.16.0
    - pykeen==1.11.0
    - temp
    
