name: mowldev39
channels:
  - conda-forge
dependencies:
  - python=3.9
  - cairo
  - deprecated
  - networkx
  - click
  - grpcio
  - JPype1=1.5.1
  - pandas
  - protobuf
  - pyyaml
  - requests
  - scikit-learn
  - urllib3
  - pytorch
  - openjdk
  - gradle
  - pip
  - pip:
    - gensim>=4.3.0
    - scipy<1.15.0
    - build
    - pykeen==1.11.0
    - numpy
    - sphinx-rtd-theme
    - sphinx-automodapi
    - nose
    - nose-exclude
    - coverage
    - pinocchio
    - flake8
    - autopep8
    - memory-profiler
    - matplotlib
  - jupyter
  - ipykernel
  - sphinx
  - sphinx-gallery
  - nbsphinx
  - mock


