name: mowldev310
channels:
  - pytorch
  - conda-forge
  - anaconda
dependencies:
  - python=3.10
  - cairo
  - deprecated
  - networkx
  - click
  - grpcio
  - JPype1=1.5.1
  - pandas
  - protobuf
  - pyyaml
  - requests
  - scikit-learn
  - urllib3
  - pytorch
  - openjdk
  - gradle
  - pip
  - pip:
    - gensim>=4.3.0
    - scipy<1.15.0	    
    - build
    - pykeen==1.11.0
    - numpy
    - sphinx-rtd-theme
    - pytest
    - pytest-faulthandler
    - coverage
    - flake8
    - autopep8
    - memory-profiler
  - jupyter
  - ipykernel
  - sphinx
  - sphinx-gallery
  - nbsphinx
  - mock


